name: okws_client
description: A simplified WebSocket client with robust reconnection handling, supporting custom headers, ping interval, and backoff strategies.
version: 0.1.0-dev.1
homepage: https://github.com/lwj1994/okws_client
repository: https://github.com/lwj1994/okws_client
environment:
  sdk: ^3.0.0

dependencies:
  
dev_dependencies:
  test: ^1.28.0
